site:
  about:
    siteName: 'Flux Claims'
    subtitle: 'Detailed Functional and Technical Documentation of FLux Claims'
    siteDescription: 'All rights reserved with Evolvus Solutions. You will need appropriate license to access and use information provided in this site. Please email your requirement to flux@evolvussolutions.com'
    avatar: '/assets/media/flux-1.png'
  theme: 'FutureImperfect'
  baseUrl: 'netlify'

theme:
  social:
    twitter: 'evolvus'
    github: 'evolvus'
    other:
      - label: 'linkedin'
        link: 'https://www.linkedin.com/company/evolvus-solutions/mycompany'
        icon: 'fa-linkedin'
  menu:
    - type: "wikiSections"
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'page'
      title: 'About'
      itemId: 'Author One'
    - type: "pages"
      atRoot: true
    - type: groupPages
      collectionType: pages
      collectionId: allPages
      groups:
        - 'group1'
        - 'group2'
        - 'group3'
  sidebar:
    - type: recentPosts
      limit: 3
      category: personal
      noWrapper: true
      template:
        - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'
  legacySearch: false
  metaComponents:
    - type: orchidSearch

services:
  generators:
    externalIndices:
      - 'https://orchid.run/meta/all.index.json'
