permalink: ':category/:year/:monthName/:slug'
categories:
  - key: 'functional'
    title: 'Functional Documentation'
  - key: 'technical'
    title: 'Technical Documentation'
authors:
  - name: 'Prashant Maroli'
    avatar: 'assets/images/prashant.jpg'
    email: 'prashant.maroli@evolvussolutions.com'
postPages:
  author: 'Author One'
  layout: single
  components:
    - type: pageContent
    - type: taxonomy
      taxonomyType: tags
    - type: taxonomy
      taxonomyType: categories
