permalink: ':category/:year/:monthName/:slug'
categories:
  - key: 'category1'
    title: 'Functional Documentation'
  - key: 'category2'
    title: 'Technical Documentation'
authors:
  - name: 'Prashant Maroli'
    avatar: 'assets/images/prashant.jpg'
    email: 'prashant.maroli@evolvussolutions.com'
postPages:
  author: 'Prashant Maroli'
  layout: single
  components:
    - type: pageContent
    - type: taxonomy
      taxonomyType: tags
    - type: taxonomy
      taxonomyType: categories
